/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculadoraOfertas;

import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author kiuub
 */
public class Metodos extends javax.swing.JFrame {

    /**
     * Creates new form calcularRaiz
     */
    
    int valorIAux;
    double valorC,decimales;
    int valorInicio;
    double porError,errorRelativo,valorX,valorXAux,valorXFinal;
    String texto;
    
    public Metodos() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    public boolean isNumberN(String num){
        boolean resp=false;
        for (int c : num.toCharArray()) {
            if(c>=48&&c<=57||c==46||c==45||c==0){
                resp=true;
            }
            else {
                resp=false;
                break;
            }
        }
        return resp;
    }
  public boolean isNumber(String num){
        boolean resp=false;
        for (int c : num.toCharArray()) {
            if(c>=48&&c<=57||c==46||c==0){
                resp=true;
            }
            else {
                resp=false;
                break;
            }
        }
        return resp;
    }
  public boolean isADot(String num){
        boolean resp=false;
        for (int c : num.toCharArray()) {
            if(c>=48&&c<=57){
                resp=true;
            }
            else {
                resp=false;
                break;
            }
        }
        return resp;
    }
   public boolean isAInt(String num){
        boolean resp=false;
        for (int c : num.toCharArray()) {
            if(c>=48&&c<=57||c==45){
                resp=true;
            }
            else {
                resp=false;
                break;
            }
        }
        return resp;
    }
   public boolean isLetter(String num){
        boolean resp=false;
        for (int c : num.toCharArray()) {
            if(c>=1&&c<=47||c>57){
                resp=true;
            }
            else {
                resp=false;
                break;
            }
        }
        return resp;
    }
}
